In [24]:
import numpy as np
import pandas as pd
import csv
from sklearn import preprocessing
from scipy.stats import anderson
train= pd.read_csv('train.csv',low_memory=False)

In [25]:
train=train.drop('user_id',1)
train=train[train['gender']!=0]

In [27]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
column_lst=['online_time','1_total_fee','3_total_fee','4_total_fee','month_traffic','contract_time','pay_times','pay_num','last_month_traffic','local_trafffic_month','local_caller_time','age','service1_caller_time','service2_caller_time','former_complaint_num','former_complaint_fee']
for i in range(len(column_lst)):
            train[column_lst[i]]=MinMaxScaler().fit_transform(train[column_lst[i]].values.reshape(-1,1))

In [20]:
train.head(5)

,service_type,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_type,...,local_trafffic_month,local_caller_time,service1_caller_time,service2_caller_time,gender,age,complaint_level,former_complaint_num,former_complaint_fee,current_service
0,4,0,0.307692,0.097163,296.2,0.078993,0.146659,0.023976,0,1,...,0.002874,0.016731,0.000000,0.034299,1,0.313131,0,0.000000,0.0,99999825
1,1,0,0.032967,0.087065,261.2,0.066910,0.121646,0.000000,1,0,...,0.129762,0.037161,0.069106,0.000000,1,0.303030,0,0.000000,0.0,90063345
2,1,0,0.040293,0.014609,70.2,0.047646,0.098514,0.016336,0,0,...,0.003995,0.004282,0.000000,0.005981,2,0.252525,0,0.000000,0.0,90109916
3,4,0,0.487179,0.028874,81.4,0.048613,0.104015,0.006214,0,0,...,0.002041,0.013914,0.014492,0.007404,1,0.444444,0,0.000000,0.0,89950166
4,4,0,0.304029,0.104084,314.08,0.098258,0.170435,0.037004,0,1,...,0.000000,0.000000,0.006829,0.030189,1,0.313131,2,0.027027,0.0,99999825

In [28]:
service_type = pd.get_dummies(train,columns=['service_type'],prefix='service_type')
contract_type = pd.get_dummies(service_type,columns=['contract_type'],prefix='contract_type')
gender=pd.get_dummies(contract_type,columns=['gender'],prefix='gender')
complaint_level=pd.get_dummies(gender,columns=['complaint_level'],prefix='complaint_level')
net_service=pd.get_dummies(complaint_level,columns=['net_service'],prefix='net_service')
train=net_service

In [31]:
train.to_csv('train_1.csv', sep=',', header=True,index=False)

In [29]:
train['current_service']=train['current_service'].replace(90063345,1)
train['current_service']=train['current_service'].replace(90109916,2)
train['current_service']=train['current_service'].replace(90155946,3)
train['current_service']=train['current_service'].replace(99104722,4)
train['current_service']=train['current_service'].replace(89016252,5)
train['current_service']=train['current_service'].replace(89016253,6)
train['current_service']=train['current_service'].replace(89016259,7)
train['current_service']=train['current_service'].replace(89950166,8)
train['current_service']=train['current_service'].replace(89950167,9)
train['current_service']=train['current_service'].replace(89950168,10)
train['current_service']=train['current_service'].replace(99999825,11)
train['current_service']=train['current_service'].replace(99999826,12)
train['current_service']=train['current_service'].replace(99999827,13)
train['current_service']=train['current_service'].replace(99999828,14)
train['current_service']=train['current_service'].replace(99999830,15)

In [30]:
train.head(10)

,is_mix_service,online_time,1_total_fee,2_total_fee,3_total_fee,4_total_fee,month_traffic,many_over_bill,contract_time,is_promise_low_consume,...,gender_1,gender_2,complaint_level_0,complaint_level_1,complaint_level_2,complaint_level_3,net_service_2,net_service_3,net_service_4,net_service_9
0,0,0.307692,0.097163,296.2,0.078993,0.146659,2.397634e-02,0,0.698113,0,...,1,0,1,0,0,0,0,0,1,0
1,0,0.032967,0.087065,261.2,0.066910,0.121646,0.000000e+00,1,0.018868,0,...,1,0,1,0,0,0,0,0,1,0
2,0,0.040293,0.014609,70.2,0.047646,0.098514,1.633622e-02,0,0.018868,0,...,0,1,1,0,0,0,0,0,1,0
3,0,0.487179,0.028874,81.4,0.048613,0.104015,6.214364e-03,0,0.018868,0,...,1,0,1,0,0,0,0,0,1,0
4,0,0.304029,0.104084,314.08,0.098258,0.170435,3.700426e-02,0,0.471698,0,...,1,0,0,0,1,0,0,0,1,0
5,0,0.164835,0.011819,36,0.043089,0.093564,1.370596e-03,0,0.245283,0,...,1,0,1,0,0,0,0,0,1,0
6,0,0.040293,0.011031,32.7,0.043462,0.095303,0.000000e+00,0,0.018868,0,...,1,0,1,0,0,0,0,0,1,0
7,0,0.245421,0.065703,66.5,0.047301,0.099557,0.000000e+00,0,0.018868,0,...,1,0,1,0,0,0,0,0,1,0
8,0,0.395604,0.038083,116,0.054136,0.109681,3.998219e-03,0,0.245283,0,...,1,0,1,0,0,0,0,0,1,0
9,0,0.102564,0.005253,19.45,0.040824,0.089596,1.376633e-08,0,0.018868,0,...,1,0,1,0,0,0,1,0,0,0

In [32]:
MinMaxScaler().fit_transform(train['2_total_fee'].values.reshape(-1,1))

ValueError: could not convert string to float: '\\N'